homeassistant:
  name: Home
  latitude: 45.5024403
  longitude: -122.7741049
  elevation: 123 # meters
  unit_system: imperial
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend, config & UI
frontend:
config:
http:
  api_password: !secret http_password
  # base_url: home.holliandtyler.com

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 10
    exclude:
     - 192.168.0.189
     - 192.168.0.1

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables state history & event logbook
history:
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather_1d
      - weather_2d
      - weather_3d
      - weather_4d
      - temp_high_record_f
      - temp_high_1d_f
      - temp_f
      - temp_low_1d_f
      - temp_low_record_f
      - precip_1d
      - precip_1d_in
      - wind_mph
      - wind_1d_mph
      - alerts
  - platform: time_date
    display_options:
      - 'date'
      - 'time'


# Text to speech
tts:
  - platform: google

# Docs here:  https://home-assistant.io/components/ifttt/
ifttt:
  key: !secret ifttt_key

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

light:
  - platform: hue

media_player:
  - platform: webostv # TODO: Autodiscovery didn't work, so manually config
  - platform: sonos
  - platform: pandora # apt-get install pianobar ffmpeg

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
